name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      build_frontend:
        description: 'Build frontend image'
        required: true
        default: 'true'
        type: boolean
      build_backend:
        description: 'Build backend image'
        required: true
        default: 'true'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_frontend == 'true' || github.event.inputs.build_backend == 'true' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build frontend image
      if: ${{ github.event.inputs.build_frontend == 'true' }}
      run: |
        cd frontend/petshealth
        docker buildx build --file Dockerfile -t petshealth-frontend:latest --output type=local,dest=../../frontend-image .

    - name: Build backend image
      if: ${{ github.event.inputs.build_backend == 'true' }}
      run: |
        cd backend/petshealth
        docker buildx build --file Dockerfile -t petshealth-backend:latest --output type=local,dest=../../backend-image .

    - name: Save Frontend Docker image as tar file
      if: ${{ github.event.inputs.build_frontend == 'true' }}
      run: |
          docker save petshealth-frontend:latest -o frontend-image.tar


    - name: Save Backend Docker image as tar file
      if: ${{ github.event.inputs.build_backend == 'true' }}
      run: |
          docker save petshealth-backend:latest -o backend-image.tar
 

    - name: Create zip file of Docker images
      run: |
        zip docker-images.zip frontend-image.tar backend-image.tar || true

    - name: Upload zip file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-images
        path: docker-images.zip
