name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      build_frontend:
        description: 'Build frontend image'
        required: true
        default: 'true'
        type: boolean
      build_backend:
        description: 'Build backend image'
        required: true
        default: 'true'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build frontend image
      if: ${{ github.event.inputs.build_frontend == 'true' }}
      run: |
        cd frontend/petshealth
        docker build -t petshealth-frontend:latest .

    - name: Build backend image
      if: ${{ github.event.inputs.build_backend == 'true' }}
      run: |
        cd backend/petshealth
        docker build -t petshealth-backend:latest .

    - name: Save Docker images as tar files
      run: |
        if [ "${{ github.event.inputs.build_frontend }}" = "true" ]; then
          docker save petshealth-frontend:latest -o petshealth-frontend.tar
        fi
        if [ "${{ github.event.inputs.build_backend }}" = "true" ]; then
          docker save petshealth-backend:latest -o petshealth-backend.tar
        fi

    - name: Create zip file of Docker images
      run: |
        zip -r petshealth-image.zip *.tar

    - name: Upload zip file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: petshealth-docker-image
        path: petshealth-image.zip
