name: Build Docker Images

on:
  workflow_dispatch:
    inputs:
      build_frontend:
        description: 'Build frontend image'
        required: true
        default: 'true'
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_frontend == 'true' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  

    - name: Build frontend image
      run: |
        cd frontend/petshealth
        docker build -t petshealth-frontend:latest .

    - name: Build frontend image
      run: |
        cd backend/petshealth
        docker build -t petshealth-backend:latest .

    - name: Save Docker image as tar file
      run: |
        docker save petshealth-frontend:latest -o petshealth-frontend.tar
        docker save petshealth-backend:latest -o petshealth-backend.tar

    - name: Create zip file of Docker image
      run: |
        zip petshealth-image.zip petshealth-frontend.tar petshealth-backend.tar

    - name: Upload zip file as artifact
      uses: actions/upload-artifact@v4  
      with:
        name: petshealth-docker-image
        path: petshealth-image.zip
